## Imports

In [1]:
import torch
import math

## Create Example Q, K, V

In [2]:
Q = torch.tensor([
    [1.0, 0.0],
    [0.0, 1.0],
    [1.0, 1.0]
])

K = torch.tensor([
    [1.0, 0.0],
    [1.0, 1.0],
    [0.0, 1.0]
])

V = torch.tensor([
    [10.0, 0.0],
    [0.0, 20.0],
    [5.0, 5.0]
])

## Print Shapes

In [3]:
print("Q Shape:", Q.shape)
print("K Shape:", K.shape)
print("V Shape:", V.shape)

Q Shape: torch.Size([3, 2])
K Shape: torch.Size([3, 2])
V Shape: torch.Size([3, 2])


## Compute Raw Attention Scores

In [4]:
scores = Q @ K.T

print(scores)

tensor([[1., 1., 0.],
        [0., 1., 1.],
        [1., 2., 1.]])


## Scale Scores

In [5]:
d_k = K.shape[-1]

print(d_k)

2


In [6]:
scaled_scores = scores / math.sqrt(d_k)

print(scaled_scores)

tensor([[0.7071, 0.7071, 0.0000],
        [0.0000, 0.7071, 0.7071],
        [0.7071, 1.4142, 0.7071]])


## Apply Softmax

In [7]:
weights = torch.softmax(
    scaled_scores,
    dim=-1
)

print(weights)

tensor([[0.4011, 0.4011, 0.1978],
        [0.1978, 0.4011, 0.4011],
        [0.2483, 0.5035, 0.2483]])


## Verify Rows Sum To 1

In [8]:
print(weights.sum(dim=-1))

tensor([1., 1., 1.])


## Use Value Vectors

In [9]:
output = weights @ V

print(output)

tensor([[ 5.0000,  9.0111],
        [ 3.9833, 10.0278],
        [ 3.7238, 11.3111]])


## Full Attention Function

Now combine everything.

In [10]:
def attention(Q, K, V):

    scores = Q @ K.T

    scaled_scores = scores / math.sqrt(
        K.shape[-1]
    )

    weights = torch.softmax(
        scaled_scores,
        dim=-1
    )

    output = weights @ V

    return output, weights

## Run Function

In [11]:
output, weights = attention(
    Q,
    K,
    V
)

print("Attention Weights")
print(weights)

print("\nOutput")
print(output)

Attention Weights
tensor([[0.4011, 0.4011, 0.1978],
        [0.1978, 0.4011, 0.4011],
        [0.2483, 0.5035, 0.2483]])

Output
tensor([[ 5.0000,  9.0111],
        [ 3.9833, 10.0278],
        [ 3.7238, 11.3111]])
